include:
  - docker/compose/app-postgres.yaml
  - docker/compose/redis.yaml
  - docker/compose/qdrant.yaml
  - docker/compose/temporal.yaml

networks:
  manudocs-network:
    driver: bridge
    name: manudocs-network

volumes:
  postgres_data:
  redis_data:
  backend_venv:
  backend_uv_cache:
  backend_logs:
  qdrant_data:
  temporal_postgresql_data:
  temporal_elasticsearch_data:
