auth:
  secret-key: "KTw174Hu9qn2TkQkFLco2cRHuout6vMMO6GOJbNmbbN"

db:
  url: "postgresql+asyncpg://manudocsuser:manudocs@localhost:5432/manudocsdb"

redis:
  url: "redis://localhost:6379/0"

emailproviders:
  # Optional if you are using resend
  resend-api-key: "resend-dev-secret"
  # Required if you are using smtp auth
  smtp-password: "smtp-dev-secret"
